version: 1

name: domain-identity-seminary-types

pipelines:
  dev:
    phases:
    - type: github
      name: GitHub
      owner: byu-oit
      repo: domain-identity-seminary-types
      branch: origin/master
    - type: codebuild
      name: Build
      build_image: aws/codebuild/nodejs:6.3.1
    - type: handel
      name: Deploy
      environments_to_deploy:
      - dev
